name=base
spring.profiles.active=dev
# suppress inspection "UnusedProperty"
springdoc.api-docs.path=/api-docs
# suppress inspection "UnusedProperty"
springdoc.swagger-ui.path=/docs
# suppress inspection "UnusedProperty"
springdoc.swagger-ui.operationsSorter=method
